name: SmartItemRemoval
main: org.stonecipher.SmartItemRemoval
author: Nickster258
version: 1.4
api-version: 1.16

commands:
  keepdrops:
    description: Toggle to allow players the option of keeping dropped items.
    usage: /<command>
    permission: smartitemremoval.toggle
    permission-message: You don't have permission!
  pickupshulkers:
    description: Toggle picking up shulker boxes.
    usage: /<command>
    permission: smartitemremoval.shulkers
    permission-message: You don't have permission!